# Generated by Django 5.0.1 on 2024-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_follow_follower_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassrootprofile',
            name='contact_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
