# Generated by Django 5.0.1 on 2024-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassrootprofile',
            name='sdg',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
