# Generated by Django 5.0.1 on 2024-03-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_grassrootprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassrootprofile',
            name='profile_icon',
            field=models.ImageField(default='noneimage', upload_to='grassroot_profile_icons/'),
            preserve_default=False,
        ),
    ]
